"""Generate env_init.sh for a given OPENCODE_ROOT (no template path in repo)."""

from __future__ import annotations

import os
from pathlib import Path

from lib.paths import templates_dir


def opencode_subprocess_env(root: Path) -> dict[str, str]:
    """
    Environment for child processes, equivalent to sourcing env_init.sh for this OPENCODE_ROOT.
    Use from Streamlit/subprocess when you cannot source into the user's interactive shell.
    """
    r = str(root.resolve())
    env = dict(os.environ)
    env["OPENCODE_ROOT"] = r
    bin_dir = f"{r}/bin"
    path = env.get("PATH", "")
    env["PATH"] = f"{bin_dir}:{path}" if path else bin_dir
    env["XDG_CONFIG_HOME"] = f"{r}/config"
    env["XDG_DATA_HOME"] = f"{r}/data"
    env["XDG_STATE_HOME"] = f"{r}/state"
    env["OPENCODE_CONFIG"] = f"{r}/config/opencode/opencode.json"
    return env


def render_env_init_script(root: Path) -> str:
    root_resolved = root.resolve()
    template = templates_dir() / "env_init.sh.template"
    if template.is_file():
        text = template.read_text(encoding="utf-8")
        return text.replace("__OPENCODE_ROOT__", str(root_resolved))
    return _builtin_script(root_resolved)


def _builtin_script(root_resolved: Path) -> str:
    r = str(root_resolved)
    return f'''# OpenCode portable environment (generated by opencode_quickstart)
export OPENCODE_ROOT="{r}"

export PATH="$OPENCODE_ROOT/bin:$PATH"
export XDG_CONFIG_HOME="$OPENCODE_ROOT/config"
export XDG_DATA_HOME="$OPENCODE_ROOT/data"
export XDG_STATE_HOME="$OPENCODE_ROOT/state"
export OPENCODE_CONFIG="$OPENCODE_ROOT/config/opencode/opencode.json"
'''


def write_env_init(root: Path) -> Path:
    out = root / "env_init.sh"
    out.write_text(render_env_init_script(root) + "\n", encoding="utf-8")
    try:
        out.chmod(out.stat().st_mode | 0o111)
    except OSError:
        pass
    return out
